hcow/config/routes.rb
Rails.application.routes.draw do
  namespace :web do
    get 'photos/index'
    get 'photos/show'
    get 'events/calendar'
    get 'events/show'
  end
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  get 'calendar/index'
  get 'control_panel/index'
  get 'simple_calendar/month_calendar'
  devise_for :users
  get 'site/home'
  get 'control_panel/index'
  resources :sponsors
  resources :photos
  resources :albums
  resources :events
  resources :pages
  resources :sections
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "site#home"
end

hcow/app/models/section.rb
class Section < ApplicationRecord
  has_many :pages
	  validates :title, :location, presence: true
end

hcow/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /sections or /sections.json
  def index
    @sections = Section.all
    authorize @sections
  end

  # GET /sections/1 or /sections/1.json
  def show
    authorize @section
  end

  # GET /sections/new
  def new
    @section = Section.new
    authorize @section
  end

  # GET /sections/1/edit
  def edit
    authorize @section
  end

  # POST /sections or /sections.json
  def create
    @section = Section.new(section_params)
    authorize @section

    respond_to do |format|
      if @section.save
        format.html { redirect_to section_url(@section), notice: "Section was successfully created." }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1 or /sections/1.json
  def update
    authorize @section
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to section_url(@section), notice: "Section was successfully updated." }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1 or /sections/1.json
  def destroy
    authorize @section
    @section.destroy

    respond_to do |format|
      format.html { redirect_to sections_url, notice: "Section was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def section_params
      params.require(:section).permit(:location, :position, :title, :visible)
    end
end

hcow/app/helpers/sections_helper.rb
module SectionsHelper
end

hcow/app/views/sections/_form.html.erb
<%= form_with(model: section) do |form| %>
  <% if section.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.number_field :position %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :visible, style: "display: block" %>
    <%= form.check_box :visible %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

hcow/app/views/sections/_section.html.erb
<div id="<%= dom_id section %>">
<table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">location</th>
      <th scope="col">Visiable</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= section.title %></th>
      <td><%if section.visible == true %> is visible <% else %> is not visible <% end %></td>
      <td><%=section.location %></td>
    </tr>
  </tbody>
</table>
</div>

hcow/app/views/sections/edit.html.erb
<h1>Editing section</h1>

<%= render "form", section: @section %>

<br>

<div>
  <%= link_to "Show this section", @section %> |
  <%= link_to "Back to sections", sections_path %>
</div>

hcow/app/views/sections/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sections</h1>

<div id="sections">
    <table class="table">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col"></th>
        <th scope="col">Visiable</th>
        <th scope="col"></th>
        <th scope="col">Location</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
  <% @sections.each do |section| %>
        <tr>
          <th scope="row"><%= section.title %></th>
          <td><%if section.visible == true %> is  <% else %> is not  <% end %></td>
          <td> visable </td>
          <td> in </td>
          <td><%=section.location %></td>
          <td> <%= link_to "Show", section, class: "btn btn-primary"%> </td>
          <td><%= link_to "Edit", section, class: "btn btn-warning"%></td>
          <td> <%= button_to "Destroy", section, method: :delete, class: "btn btn-danger" %></td>
        </tr>
  <% end %>
    </tbody>
  </table>

</div>

<%= link_to "New Section", new_section_path, class: "btn btn-success"%>
<%= link_to "Back", control_panel_index_path, class: "btn btn-warning"%>

hcow/app/views/sections/new.html.erb
<h1>New section</h1>

<%= render "form", section: @section %>

<br>

<div>
  <%= link_to "Back to sections", sections_path %>
</div>

hcow/app/views/sections/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @section %>

<div>
<%= link_to "Back", sections_path, class: "btn btn-primary"%>
</div>