hcow/config/routes.rb
Rails.application.routes.draw do
  namespace :web do
    get 'photos/index'
    get 'photos/show'
    get 'events/calendar'
    get 'events/show'
  end
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  get 'calendar/index'
  get 'control_panel/index'
  get 'simple_calendar/month_calendar'
  devise_for :users
  get 'site/home'
  get 'control_panel/index'
  resources :sponsors
  resources :photos
  resources :albums
  resources :events
  resources :pages
  resources :sections
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "site#home"
end

hcow/app/models/album.rb
class Album < ApplicationRecord
  has_many :photos
    validates :title, :description, presence: true
end

hcow/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

hcow/app/models/event.rb
class EventValidator < ActiveModel::Validator
  def validate(record)
    if Event.where(featured: true).length() >= 4 && record.featured == true
      record.errors.add :event, "Reached Maximum of Featured Events (4)"
    end
  end
end

class Event < ApplicationRecord
  has_one_attached :photo
  validates :title, :eventstart, :eventend, presence: true
  include ActiveModel::Validations
  validates_with EventValidator
end

hcow/app/models/page.rb
class Page < ApplicationRecord
  belongs_to :section
	  validates :title, presence: true
	has_one_attached :doc
end

hcow/app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :album
  has_one_attached :image
end

hcow/app/models/section.rb
class Section < ApplicationRecord
  has_many :pages
	  validates :title, :location, presence: true
end

hcow/app/models/sponsor.rb
class Sponsor < ApplicationRecord
  has_one_attached :image
  validates :title, presence: true
end

hcow/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

hcow/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
    authorize @pages
  end

  # GET /pages/1 or /pages/1.json
  def show
    authorize @page
  end

  # GET /pages/new
  def new
    @page = Page.new
    authorize @page
  end

  # GET /pages/1/edit
  def edit
    authorize @page
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)
    authorize @page

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_url(@page), notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    authorize @page
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page), notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy
    authorize @page

    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.require(:page).permit(:title, :section_id, :position, :page_type, :destination, :visible, :content, :doc)
    end
end

hcow/app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
  end
end

hcow/app/helpers/albums_helper.rb
module AlbumsHelper
end

hcow/app/helpers/application_helper.rb
module ApplicationHelper
end

hcow/app/helpers/calendar_helper.rb
module CalendarHelper
end

hcow/app/helpers/control_panel_helper.rb
module ControlPanelHelper
end

hcow/app/helpers/events_helper.rb
module EventsHelper
end

hcow/app/helpers/pages_helper.rb
module PagesHelper
end

hcow/app/helpers/photos_helper.rb
module PhotosHelper
end

hcow/app/helpers/sections_helper.rb
module SectionsHelper
end

hcow/app/helpers/site_helper.rb
module SiteHelper
end

hcow/app/helpers/sponsors_helper.rb
module SponsorsHelper
end

hcow/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hcow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= tinymce_assets %>
    <script type="text/javascript" src="/assets/tinymce.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="blue">

    <!-- Navigation Bar -->
    <nav class="navbar navbar-dark red py-4">
      <div class="container-fluid">
        <a class="navbar-brand text-white bold-text text-uppercase ps-3 fs-3" href="/site/home">Harmony Club of Worcester</a>
        <button class="navbar-toggler ms-auto blue" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>
    <div class="collapse" id="navbarToggleExternalContent">
      <div class="red bold-text text-uppercase">
        <ul class="navbar-nav">
          <li class="text-white text-uppercase bold-text py-2 px-0 px-lg-3">
            <%= link_to "Home", site_home_path, class: "nav-link" %>
          </li>
          <% if(user_signed_in?) %>
            <li class="text-white text-uppercase bold-text py-2 px-0 px-lg-3">
              <%= link_to "Control Panel", control_panel_index_path, class: "nav-link" %>
            </li>
          <% end %>
          <% Section.where(visible: true).each do |s| %>
            <li class="nav-item dropdown mx-0 mx-lg-1">
              <a class="dropdown-toggle nav-link py-3 px-0 px-lg-3 rounded text-white navbarDropdown" role="button" aria-expanded="false" data-bs-toggle="dropdown" href="#">
                <%= s.title %>
              </a>
              <ul class="dropdown-menu" aria-label="navbarDropdown">
                <% s.pages.where(visible: true).each do |p| %>
                  <% if p.page_type == "Basic Page" %>
                    <%= link_to p.title, page_path(id: p.id), class: "dropdown-item" %>
                  <% elsif p.page_type == "Internal Link" %>
                    <%= link_to p.title, p.destination, class: "dropdown-item" %>
                  <% elsif p.page_type == "External Link" %>
                    <%= link_to p.title, p.destination, class: "dropdown-item", target: :_blank %>
                  <% elsif p.page_type == "PDF" %>
                    <%= link_to p.title, page_path(id: p.id), class: "dropdown-item" %>
                  <% end %>
                <% end %>
              </ul>
            </li>
          <% end %>
          <div class="px-3 pb-3">
            <% if(user_signed_in?) %>
              <li class="text-white text-uppercase bold-text">
                <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger"  %>
              </li>
            <% else %>
              <li class="text-white text-uppercase bold-text">
                <%= button_to "Login", new_user_session_path, class: "btn btn-secondary" %>
              </li>
            <% end %>
          </div>
        </ul>
      </div>
    </div>

    <!-- Page Content -->
    <div class="container white content topPadding vh-auto pb-5">
      <div class="container white">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <%= yield %>
        <br><br><br><br>
      </div>
    </div>

    <!-- Footer -->
    <div id="footer">
      <div id="footer-container" class="page-container red text-light">
        <div class="content-wrap">
          <div class="text-center border-bottom border-light">
            <a class="text-light text-decoration-none" href="/">Harmony Club of Worcester | <%= @current_year %></a>
          </div>
          <div class="justify-content-center">
            <!-- @sections.each do |s| -->
              <div class="text-center">
                <h6 class="d-inline"><!-- s.title -->title goes here<h6>
                <ul class="d-inline footer-list"><li></li><li></li><li></li>stuff goes here</ul>
              </div>
            <!-- end -->
          </div>
        </div>
      </div>
    </div>

  </body>
</html>

hcow/app/views/pages/_form.html.erb
<div data-controller="page">
  <%= form_with(model: page) do |form| %>
    <% if page.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

        <ul>
          <% page.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :section_id, style: "display: block" %>
      <%= form.select(:section_id, Section.all.collect {|s| [ s.title, s.id ] }, { include_blank: false }, class: "rounded") %>
    </div>

    <div>
      <%= form.label :position, style: "display: block" %>
      <%= form.number_field :position %>
    </div>

    <div>
      <%= form.label :page_type, style: "display: block" %>
      <%= form.select :page_type, ["", "Basic Page", "Internal Link", "External Link", "PDF"], {}, data: {action: "change->page#toggle", "page_target": "select"} %>
    </div>

    <div>
      <%= form.label :visible, style: "display: block" %>
      <%= form.check_box :visible %>
    </div>

    <div data-page-target="destination" style="display: none">
      <%= form.label :destination, style: "display: block" %>
      <%= form.text_field :destination %>
    </div>

    <div data-page-target="content" style="display: none">
      <%= form.label :content, style: "display: block" %>
      <p class="text-muted">If text editor doesn't appear, refresh the page | also for easy shortcuts use, click the help button on the editor</p>
      <%= form.text_area :content, :class => "tinymce" %>
      <%= tinymce %>
    </div>

    <div data-page-target="fileSelector" style="display: none">
      <%= form.label :doc, style: "display: block" %>
      <%= form.file_field :doc %>
    </div>

    <div class="py-3">
      <%= form.submit %>
    </div>
  <% end %>
</div>

hcow/app/views/pages/_page.html.erb
<div id="<%= dom_id page %>">
<table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">location</th>
      <th scope="col">Visiable</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= page.title %></th>
      <td><%if page.visible == true %> is visible <% else %> is not visible <% end %></td>
      <td><%=page.destination %></td>
      <td><%= link_to "Edit", edit_page_path(@page), class: "btn btn-warning"%></td>
      <td> <%= button_to "Destroy", @page, method: :delete, class: "btn btn-danger" %></td>
    </tr>
  </tbody>
</table>
</div>

hcow/app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", @page %> |
  <%= link_to "Back to pages", pages_path %>
</div>

hcow/app/views/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pages</h1>

<div id="pages">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col"></th>
        <th scope="col">Visiable</th>
        <th scope="col"></th>
        <th scope="col">Location</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
  <% @pages.each do |page| %>
        <tr>
          <th scope="row"><%= page.title %></th>
          <td><%if page.visible == true %> is  <% else %> is not  <% end %></td>
          <td> visable </td>
          <td> in </td>
          <td><%=page.destination %></td>
          <td> <%= link_to "Show", page, class: "btn btn-primary"%> </td>
          <td> <%= link_to "Edit", edit_page_path(page), class: "btn btn-warning"%> </td>
          <td> <%= button_to "Destroy", page, method: :delete, class: "btn btn-danger" %> </td>
        </tr>
  <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New page", new_page_path, class: "btn btn-success"%>
<%= link_to "Back", control_panel_index_path, class: "btn btn-warning"%>

hcow/app/views/pages/new.html.erb
<h1>New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path %>
</div>

hcow/app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<h1>
 <%= @page.title %>
</h1><br>

<div>
 <%= sanitize @page.content.html_safe %>
</div>

<div>
 <% if @page.doc.attached? %>
  <iframe src=<%= pdfjs.full_path(file: @page.doc) %> style="border: 0" width="100%" height="700" frameborder="0" scrolling="yes"></iframe>
 <% end %>
</div>

<br>

hcow/app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

hcow/app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading text-center" >
    <%= link_to t('simple_calendar.previous', default: '<'), calendar.url_for_previous_view, class: "btn btn-danger" %>
    <font size="+10"><span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span></font>
    <%= link_to t('simple_calendar.next', default: '>'), calendar.url_for_next_view, class: "btn btn-success" %>
  </div>

  <table class="table table-striped" id="overflowCalendar">
    <thead class = "cBorder">
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th class = "cBorder"><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody class = "cBorder">
      <% date_range.each_slice(7) do |week| %>
        <tr class = "cBorder">
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <div class="pb-4">
                <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                  <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
                <% else %>
                  <% passed_block.call day, sorted_events.fetch(day, []) %>
                <% end %>
                <% Event.all.each do |e| %>
                  <% if day <= e.eventstart.to_date && day >= e.eventend.to_date %>
                    <div>
                      <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#eventModal">
                        <%= e.title %>
                      </button>

                      <div class="modal fade" id="eventModal" tabindex="-1" aria-labelledby="eventModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h1 class="modal-title fs-5" id="eventModalLabel"><%= e.title %></h1>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                              <div class="text-center"><%= e.details %></div>
                              <div class="text-center">Starts: <%= e.eventstart %></div>
                              <div class="text-center">Ends: <%= e.eventend %></div>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  <% else %>
                    <p> </p>
                  <% end %>
                <% end %>
                <br>
              </div>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

hcow/app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>