hcow/config/routes.rb
Rails.application.routes.draw do
  namespace :web do
    get 'photos/index'
    get 'photos/show'
    get 'events/calendar'
    get 'events/show'
  end
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  get 'calendar/index'
  get 'control_panel/index'
  get 'simple_calendar/month_calendar'
  devise_for :users
  get 'site/home'
  get 'control_panel/index'
  resources :sponsors
  resources :photos
  resources :albums
  resources :events
  resources :pages
  resources :sections
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "site#home"
end

hcow/app/models/album.rb
class Album < ApplicationRecord
  has_many :photos
    validates :title, :description, presence: true
end

hcow/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /albums or /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to album_url(@album), notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to album_url(@album), notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, :description)
    end
end

hcow/app/helpers/albums_helper.rb
module AlbumsHelper
end

hcow/app/views/albums/_album.html.erb
<div id="<%= dom_id album %>">
<table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= album.title %></th>
      <td><%=album.description %></td>
    </tr>
  </tbody>
</table>
</div>


<h2>Photos:</h2>

<div class="row">
  <% album.photos.each do |p| %>
    <div class="col-lg-3">
      <div class="card" style="width: 18rem;">
        <% if p.image.attached? %>
          <%= image_tag(p.image) %>
        <% else %>
          <p>no image attached</p>
        <% end %>
        <div class="card-body">
          <h5 class="card-title text-center"><%= p.title %></h5>
          <p class="card-text text-center"><%= p.description %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

hcow/app/views/albums/_form.html.erb
<%= form_with(model: album) do |form| %>
  <% if album.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

hcow/app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Show this album", @album %> |
  <%= link_to "Back to albums", albums_path %>
</div>

hcow/app/views/albums/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Albums</h1>

<div id="albums">
    <table class="table">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
  <% @albums.each do |album| %>
        <tr>
          <th scope="row"><%= album.title %></th>
          <td><%=album.description %></td>
          <td> <%= link_to "Show", album, class: "btn btn-primary"%> </td>
          <td><%= link_to "Edit", edit_album_path(id: album.id), class: "btn btn-warning"%></td>
          <td> <%= button_to "Destroy", album, method: :delete, class: "btn btn-danger" %></td>
        </tr>
  <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New Album", new_album_path, class: "btn btn-success"%>
<%= link_to "Back", control_panel_index_path, class: "btn btn-warning"%>

hcow/app/views/albums/new.html.erb
<h1>New album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Back to albums", albums_path %>
</div>

hcow/app/views/albums/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @album %>

<div>
<%= link_to "Back", albums_path, class: "btn btn-primary"%>
</div>