hcow/config/routes.rb
Rails.application.routes.draw do
  namespace :web do
    get 'photos/index'
    get 'photos/show'
    get 'events/calendar'
    get 'events/show'
  end
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  get 'calendar/index'
  get 'control_panel/index'
  get 'simple_calendar/month_calendar'
  devise_for :users
  get 'site/home'
  get 'control_panel/index'
  resources :sponsors
  resources :photos
  resources :albums
  resources :events
  resources :pages
  resources :sections
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "site#home"
end

hcow/app/models/sponsor.rb
class Sponsor < ApplicationRecord
  has_one_attached :image
  validates :title, presence: true
end

hcow/app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_action :set_sponsor, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /sponsors or /sponsors.json
  def index
    @sponsors = Sponsor.all
  end

  # GET /sponsors/1 or /sponsors/1.json
  def show
  end

  # GET /sponsors/new
  def new
    @sponsor = Sponsor.new
  end

  # GET /sponsors/1/edit
  def edit
  end

  # POST /sponsors or /sponsors.json
  def create
    @sponsor = Sponsor.new(sponsor_params)

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to sponsor_url(@sponsor), notice: "Sponsor was successfully created." }
        format.json { render :show, status: :created, location: @sponsor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sponsors/1 or /sponsors/1.json
  def update
    respond_to do |format|
      if @sponsor.update(sponsor_params)
        format.html { redirect_to sponsor_url(@sponsor), notice: "Sponsor was successfully updated." }
        format.json { render :show, status: :ok, location: @sponsor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1 or /sponsors/1.json
  def destroy
    @sponsor.destroy

    respond_to do |format|
      format.html { redirect_to sponsors_url, notice: "Sponsor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sponsor
      @sponsor = Sponsor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sponsor_params
      params.require(:sponsor).permit(:title, :website, :image)
    end
end

hcow/app/helpers/sponsors_helper.rb
module SponsorsHelper
end

hcow/app/views/sponsors/_form.html.erb
<%= form_with(model: sponsor) do |form| %>
  <% if sponsor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sponsor.errors.count, "error") %> prohibited this sponsor from being saved:</h2>

      <ul>
        <% sponsor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :website, style: "display: block" %>
    <%= form.text_field :website %>
  </div>
  
  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

hcow/app/views/sponsors/_sponsor.html.erb
<div id="<%= dom_id sponsor %>">
  <div class="row">
    <div class="col-lg-3">
      <div class="card" style="width: 18rem;">
        <% if sponsor.image.attached? %>
          <%= image_tag(sponsor.image) %>
        <% else %>
          <p>no image attached</p>
        <% end %>
        <div class="card-body">
          <h5 class="card-title text-center"><%= sponsor.title %></h5>
          <p class="card-text text-center"><%= sponsor.website %></p>
        </div>
      </div>
    </div>
  </div>
</div>

hcow/app/views/sponsors/edit.html.erb
<h1>Editing sponsor</h1>

<%= render "form", sponsor: @sponsor %>

<br>

<div>
  <%= link_to "Back to sponsors", sponsors_path, class: "btn btn-secondary" %>
</div>

hcow/app/views/sponsors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sponsors</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Website</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @sponsors.all.each do |s| %>
      <tr>
        <th scope="row"><%= s.title %></th>
        <td><%= s.website %></td>
        <td><%= link_to "Show", sponsor_path(id: s.id), class: "btn btn-primary" %></td>
        <td><%= link_to "Edit", edit_sponsor_path(id: s.id), class: "btn btn-warning"%></td>
        <td> <%= button_to "Destroy", s, method: :delete, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New sponsor", new_sponsor_path, class: "btn btn-success" %>
<%= link_to "Back", control_panel_index_path, class: "btn btn-warning"%>

hcow/app/views/sponsors/new.html.erb
<h1>New sponsor</h1>

<%= render "form", sponsor: @sponsor %>

<br>

<div>
  <%= link_to "Back to sponsors", sponsors_path %>
</div>

hcow/app/views/sponsors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sponsor %>

<div>
  <%= link_to "Back to sponsors", sponsors_path, class: "btn btn-secondary" %>
</div>